# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
   app.client:
    class: indexBundle\Form\Type\clientFormType
    tags:
        - { name: form.type }